apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}-service
spec:
  selector:
    app: {{ include "kafka.fullname" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  type: {{ .Values.service.type | default "ClusterIP"}}