apiVersion: v1
kind: Service
metadata: {{ $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  name: {{ $fullname }}-service
spec:
  selector:
    app: {{ $fullname }}
  ports:
  - port: {{ .Values.service.port | default 80 | int }}
    targetPort: {{ .Values.pod.port | int }} 
  {{- if .Values.ingress.enabled }}
  type: {{ .Values.service.type | default "ClusterIP"}}
  {{- else }}
  type: LoadBalancer
  {{- end }}