version: '3.4'

networks:
  pdi.bacen:
    driver: bridge
  pdi.vulture:
    driver: bridge
  pdi.star:
    driver: bridge
  pdi.infra:
    driver: bridge

services:
  bacen:
    image: ${PROJECT_NAMESPACE}.bc
    container_name: ${PROJECT_NAME}.bacen
    build:
      context: ./src
      dockerfile: Bacen/Dockerfile
    depends_on:
      - mongo
      - kafka
    ports:
      - 5293:80
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNET_ENV}
    networks:
      - pdi.bacen

  mongo:
    image: mongo
    container_name: ${PROJECT_NAME}.mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    networks:
      - pdi.bacen
      - pdi.vulture
      - pdi.star
      - pdi.infra

  mongo-express:
    image: mongo-express
    container_name: ${PROJECT_NAME}.mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017
    networks:
      - pdi.infra

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: ${PROJECT_NAME}.zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - pdi.infra

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: ${PROJECT_NAME}.Kafka
    depends_on:
      - zookeeper
    ports:
        - "2181:2181"
        - "9092:9092"
    environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - pdi.bacen
      - pdi.vulture
      - pdi.star
      - pdi.infra

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: ${PROJECT_NAME}.kafka-ui
    depends_on:
      - kafka
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=PLAINTEXT
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
    ports:
        - 8082:8080
    networks:
      - pdi.infra

  init-kafka:
    image: confluentinc/cp-zookeeper:latest
    container_name: ${PROJECT_NAME}.init-kafka
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    networks:
      - pdi.infra
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:29092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic bacen.entries --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic bacen.claims --replication-factor 1 --partitions 1

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:29092 --list
      "