kind: ConfigMap
apiVersion: v1
metadata: 
  name: {{ include "apibank.fullname" . }}-configmap
  namespace: default
data:
  DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE: "false"
  MONGO_USER: "{{ .Values.mongodb.user }}"
  MONGO_SERVICE: "{{ .Values.mongodb.service }}"
  MONGO_PORT: "{{ .Values.mongodb.port  | default 27017 }}"
  Mongo__Database: "{{.Values.mongodb.databasename }}" 
  Kafka__Configuration__BootstrapServers: {{ .Values.kafka.bootstrapServers | quote }}