apiVersion: apps/v1
kind: Deployment
metadata: {{ $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  name: {{ $fullname }}-deployment
  labels:
    chart: "{{ .Release.Name }}-{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ $fullname }}
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app: {{ $fullname }}
    spec:
      {{- if .Values.pod.initContainer.enabled }}
      initContainers:
      - name: init
        image: confluentinc/cp-zookeeper:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo -e 'Creating kafka topics...'
          {{- range .Values.pod.initContainer.topics }}
            kafka-topics --bootstrap-server {{ $.Values.kafka.bootstrapServers }} --create --if-not-exists --topic {{ .topic.name }} --replication-factor {{ .topic.replicationFactor }} --partitions {{ .topic.partitions }}
          {{- end}}
            echo -e 'Successfully created the following topics:'
            kafka-topics --bootstrap-server {{ $.Values.kafka.bootstrapServers }} --list        
      {{- end}}
      containers:
      - name: {{ $fullname }}
        image: "{{ .Values.image }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.pod.port | int }}
        envFrom:
        - configMapRef:
            name: {{ $fullname }}-configmap
        env:
        - name: "MONGODB_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: {{ $fullname }}-secret
              key: mongodb-password    
        - name: "Mongo__ConnectionString"
          value: "mongodb://$(MONGO_USER):$(MONGODB_PASSWORD)@$(MONGO_SERVICE):$(MONGO_PORT)" 
        {{- if .Values.bacen.enabled }}
        - name: "Bacen__Url"
          value: "{{ .Values.bacen.url }}"
        {{- end}}
        {{- if .Values.pod.liveness.enabled }}        
        livenessProbe:
          httpGet:
            path: {{ .Values.pod.liveness.path | default "/"}}
            port: {{ .Values.pod.port | int }}
        {{- end}}
        {{- if .Values.pod.readiness.enabled }}
        readinessProbe:
          httpGet:
            path: {{ .Values.pod.readiness.path | default "/"}}
            port: {{ .Values.pod.port | int }}
        {{- end}}
        resources:
{{ toYaml .Values.pod.resources | indent 10 }}