apiVersion: v1
kind: Secret
metadata: {{ $fullname := printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
  name: {{ $fullname }}-secret
type: Opaque
data:
  mongodb-password: {{ .Values.mongodb.password | b64enc }}