apiVersion: v1
kind: Service
metadata: 
  name: {{ include "apibank.fullname" . }}-service
  labels:
    chart: "{{ .Release.Name }}-{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    app: {{ include "apibank.fullname" . }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.pod.port }}
  {{- if .Values.ingress.enabled }}
  type: {{ .Values.service.type | default "ClusterIP"}}
  {{- else }}
  type: LoadBalancer
  {{- end }}