apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zookeeper.fullname" . }}-deployment
  labels:
    chart: "{{ .Release.Name }}-{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:  
  selector:
    matchLabels:
      app: {{ include "zookeeper.fullname" . }}
  replicas: {{ .Values.replicaCount }}  
  template:
    metadata:      
      labels:
        app: {{ include "zookeeper.fullname" . }}
    spec:     
      containers:
        - name: {{ include "zookeeper.fullname" . }}          
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - name: clientport
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: "ZOOKEEPER_CLIENT_PORT"
              value: "{{ .Values.service.port }}"
            - name: "ZOOKEEPER_TICK_TIME"
              value: "{{ .Values.tickTime }}"