replicaCount: 1
image: leandroalves86/bc

service:
  type: ClusterIP
  port: 80

pod:
  initContainer:
    enabled: true
    topics:
      - topic:
          name: "bacen.entries"
          partitions: 1
          replicationFactor: 1
      - topic:
          name: "bacen.claims"
          partitions: 1
          replicationFactor: 1
  port: 80
  liveness: 
    enabled: true 
    path: /hc
  readiness:
    enabled: false 
  resources:
    limits:
      memory: "300Mi"
      cpu: "250m"

mongodb:
  user: root
  password: root123Mudar
  service: mongo-mongodb.default.svc.cluster.local
  port: 27017
  databasename: bacen

kafka:
  bootstrapServers: kafka-api-bank-service:9092

ingress:
  host: bc.leandroalves.dev.br