replicaCount: 1
image: leandroalves86/star.accounts

service:
  type: ClusterIP
  port: 80

pod:
  port: 80
  liveness: 
    enabled: true 
    path: /hc
  readiness:
    enabled: false 
  resources:
    limits:
      memory: "300Mi"
      cpu: "250m"

mongodb:
  user: root
  password: root123Mudar
  service: mongo-mongodb.default.svc.cluster.local
  port: 27017
  databasename: star.accounts

kafka:
  bootstrapServers: kafka.default.svc.cluster.local:9092

bacen:
  enabled: true
  url: "http://bacen-api-bank-service.default.svc.cluster.local"