fullname: "star-claims"
replicaCount: 1
image: leandroalves86/star.claims

service:
  type: ClusterIP
  port: 80

pod:
  initContainer:
    enabled: true
    topics:
      - topic:
          name: "star.claims"
          partitions: 1
          replicationFactor: 1
  port: 80
  liveness: 
    enabled: true 
    path: /hc
  readiness:
    enabled: false 
  resources:
    limits:
      memory: "300Mi"
      cpu: "250m"

mongodb:
  user: root
  password: root123Mudar
  service: mongo-service.default.svc.cluster.local
  port: 27017
  databasename: star.claims

kafka:
  bootstrapServers: kafka-api-bank-service.default.svc.cluster.local:9092

bacen:
  enabled: true
  url: "http://bacen-service.default.svc.cluster.local"

ingress:
  host: star.claims.leandroalves.dev.br