{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ include "mongo-express.fullname" . }}-deployment
  labels:
    chart: "{{ .Release.Name }}-{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ include "mongo-express.fullname" . }}
  replicas: {{ default 1 .Values.replicaCount | int }}
  template:
    metadata:
      labels:
        app: {{ include "mongo-express.fullname" . }}
    spec:
      containers:
      - name: {{ include "mongo-express.fullname" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.pod.port | default 8081 | int }}
        envFrom:
        - configMapRef:
            name: {{ include "mongo-express.fullname" . }}-configmap
        env:  
        - name: "MONGODB_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: {{ include "mongo-express.fullname" . }}-secret
              key: mongodb-password
        - name: "ME_CONFIG_MONGODB_URL"
          value: "mongodb://$(MONGODB_USERNAME):$(MONGODB_PASSWORD)@$(MONGO_SERVICE):$(MONGO_PORT)/"
{{ toYaml .Values.pod.resources | indent 10 }}                 
{{- end -}}