{{- if .Values.enabled -}}
{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: {{ include "mongo-express.fullname" . }}-ingress
  labels:
    name: {{ include "mongo-express.fullname" . }}-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ include "mongo-express.fullname" . }}-service
            port: 
              number: {{ .Values.service.port | default 80 | int}}
{{ end }} 
{{ end }}           