{{- if .Values.enabled -}}
apiVersion: v1
kind: Secret
metadata: 
  name: {{ include "mongo-express.fullname" . }}-secret
type: Opaque
data:
  mongodb-password: {{ toString .Values.mongo.password |  b64enc }}
{{ end }}