{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata: 
  name: {{ include "mongo-express.fullname" . }}-service
spec:
  selector:
    app: {{ include "mongo-express.fullname" . }}
  ports:
  - port: {{ .Values.service.port | default 80 | int }}
    targetPort: {{ .Values.pod.port | int }} 
  {{- if .Values.ingress.enabled }}
  type: {{ .Values.service.type | default "ClusterIP"}}
  {{- else }}
  type: LoadBalancer
  {{- end }}
{{- end }}