apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mongo.fullname" . }}-deployment
  labels:
    chart: "{{ .Release.Name }}-{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    matchLabels:
      app: {{ include "mongo.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "mongo.fullname" . }}
    spec:
      containers:
        - name: {{ include "mongo.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: mongo
          envFrom:
          - secretRef:
              name: {{ include "mongo.fullname" . }}-secret