apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongo.fullname" . }}-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongoexpress.mongo.user | b64enc }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongoexpress.mongo.password | b64enc }}