replicaCount: 1

image:
  repository: confluentinc/cp-zookeeper
  pullPolicy: IfNotPresent
  tag: "latest"

resources: 
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi

service:
  port: 2181

tickTime: 2000