apiVersion: v1
kind: Service
metadata:
  name: {{ include "webserver.fullname" . }}-service
spec:
  selector:
    app: {{ include "webserver.fullname" . }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.internalPort }}