# helm install my-kafka-ui kafka-ui/kafka-ui

service:
  type: LoadBalancer
  port: 80
  loadBalancerIP: 172.28.255.210
yamlApplicationConfig:
  kafka:
    clusters:
      - name: k8s
        bootstrapServers: kafka.default.svc.cluster.local:9092
ingress:
  enabled: true
  host: kafka-ui.leandroalves.dev.br
  ingressClassName: nginx
