fullname: "apibank"
replicaCount: 1
image: leandroalves86.bc

service:
  type: ClusterIP
  port: 80

pod:
  initContainer:
    enabled: false
    topics: []
  port: 80
  liveness: 
    enabled: true 
    path: /hc
  readiness:
    enabled: false 
  resources:
    limits:
      memory: "300Mi"
      cpu: "250m"

mongodb:
  user: root
  password: root123Mudar
  service: mongo-service.default.svc.cluster.local
  port: 27017
  databasename: bacen

kafka:
  bootstrapServers: kafka-headless.default:9092

bacen:
  enabled: false
  url: ""

ingress:
  enabled: true
  host: bacen.local