image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "latest"

fullname: ""

service:
  type: ClusterIP
  port: 80
  internalPort: 80

ingress:
  className: nginx
  host: chart-example.local

resources:
  limits:
    cpu: 25m
    memory: 32Mi
  requests:
    cpu: 12m
    memory: 16Mi

autoscaling:
  minReplicas: 1
  maxReplicas: 10
  cpuUtilization: 80
  memoryUtilization: 80
  stabilizationWindowSeconds: 300
  policiesPeriodSeconds: 15
